package com.appspot.demo.server.paypal.model;

public enum ActionType {
	NEWUSER, NEWINVOICE, NEWTRANSACTION, NEWPACKAGE, NEWCUSTOMER, CANCELTRANSACTION, FAILEDUSER, FAILEDINVOICE, FAILEDTRANSACTION, COMPLETEDTRANSACTION, FAILEDPACKAGE, FAILEDCUSTOMER, NOTVERIFIEDIPN, VERIFIEDIPN
}
